<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>MyChart.UI</RootNamespace>
    <AssemblyName>MyChart.UI</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp.Views.WPF" Version="2.88.9" />
    <ProjectReference Include="..\MyChart.Core\MyChart.Core.csproj" />
  </ItemGroup>
</Project>
