using System.Security.Cryptography;
using System.Text;
using MyChart.Core.Plugins.Manifest;

namespace MyChart.Generator.Engine.Operations;

/// <summary>
/// PG3.05 CatalogGenerator — PluginCatalog.g.cs and IconCatalog.g.cs.
/// Active RepoRoot components only; ordinal sort; LF; header with manifest-hash.
/// </summary>
public static class CatalogGenerator
{
    public sealed class ComponentInput
    {
        public required string ComponentId { get; init; }
        public required string Kind { get; init; } // DataTool | CodeTool | Icon
        public required bool Active { get; init; }
        public required string ManifestJson { get; init; }
        public string? DefinitionJson { get; init; }
        public string? IconKey { get; init; }
        public string? GeometryPathData { get; init; }
        public string? RegistrationTypeName { get; init; } // CodeTool only
    }

    public static (string PluginCatalogCs, string IconCatalogCs, string ManifestHash) Generate(
        IEnumerable<ComponentInput> components)
    {
        var active = components
            .Where(c => c.Active)
            .OrderBy(c => c.ComponentId, StringComparer.Ordinal)
            .ToList();

        // sha256 of sorted manifest hashes (one line per component, joined)
        var manifestHashes = active
            .Select(c => ManifestIO.Sha256Normalized(c.ManifestJson))
            .OrderBy(h => h, StringComparer.Ordinal)
            .ToList();
        var combined = string.Join("\n", manifestHashes) + (manifestHashes.Count > 0 ? "\n" : "");
        var headerHash = ManifestIO.Sha256Normalized(combined);

        var pluginCs = BuildPluginCatalog(active, headerHash);
        var iconCs = BuildIconCatalog(active, headerHash);
        return (pluginCs, iconCs, headerHash);
    }

    /// <summary>Scan RepoRoot Components folders + optional Icon* folders under a components root.</summary>
    public static List<ComponentInput> ScanRepoComponents(string componentsRoot)
    {
        var list = new List<ComponentInput>();
        if (!Directory.Exists(componentsRoot))
            return list;

        foreach (var dir in Directory.EnumerateDirectories(componentsRoot).OrderBy(d => d, StringComparer.Ordinal))
        {
            var manifestPath = Path.Combine(dir, "Manifest.json");
            if (!File.Exists(manifestPath))
                continue;

            ComponentManifest manifest;
            try { manifest = ManifestIO.ReadFile(manifestPath); }
            catch { continue; }

            var id = manifest.ComponentId;
            if (string.IsNullOrEmpty(id))
                id = Path.GetFileName(dir);

            string? def = null;
            var defPath = Path.Combine(dir, "Definition.json");
            if (File.Exists(defPath))
                def = File.ReadAllText(defPath).Replace("\r\n", "\n").Replace('\r', '\n');

            string? geo = null;
            var geoPath = Path.Combine(dir, "Geometry.txt");
            if (File.Exists(geoPath))
                geo = File.ReadAllText(geoPath).Trim().Replace("\r\n", "\n").Replace('\r', '\n');

            list.Add(new ComponentInput
            {
                ComponentId = id,
                Kind = manifest.Kind,
                Active = manifest.Active,
                ManifestJson = File.ReadAllText(manifestPath).Replace("\r\n", "\n").Replace('\r', '\n'),
                DefinitionJson = def,
                IconKey = manifest.IconKey,
                GeometryPathData = geo,
                RegistrationTypeName = manifest.Kind == "CodeTool" ? $"{id}Registration" : null
            });
        }

        return list;
    }

    private static string BuildPluginCatalog(List<ComponentInput> active, string headerHash)
    {
        var tools = active.Where(c => c.Kind is "DataTool" or "CodeTool").ToList();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file is generated by the component catalog generator.");
        sb.AppendLine("// Do not edit manually.");
        sb.AppendLine($"// manifest-hash: {headerHash}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("namespace MyChart.Plugins;
");
        sb.AppendLine("/// <summary>Auto-generated catalog of first-party plugin components.</summary>");
        sb.AppendLine("public static class PluginCatalog");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string ManifestHash = \"{headerHash}\";");
        sb.AppendLine();
        sb.AppendLine("    public readonly record struct Entry(");
        sb.AppendLine("        string ComponentId,");
        sb.AppendLine("        string Kind,");
        sb.AppendLine("        string ManifestJson,");
        sb.AppendLine("        string? DefinitionJson);");
        sb.AppendLine();
        sb.AppendLine("    public static IReadOnlyList<Entry> Entries { get; } = new Entry[]");
        sb.AppendLine("    {");
        for (int i = 0; i < tools.Count; i++)
        {
            var t = tools[i];
            var comma = i < tools.Count - 1 ? "," : "";
            sb.AppendLine($"        new Entry(");
            sb.AppendLine($"            {CsString(t.ComponentId)},");
            sb.AppendLine($"            {CsString(t.Kind)},");
            sb.AppendLine($"            {CsString(t.ManifestJson)},");
            sb.AppendLine($"            {(t.DefinitionJson is null ? "null" : CsString(t.DefinitionJson))}){comma}");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString().Replace("\r\n", "\n");
    }

    private static string BuildIconCatalog(List<ComponentInput> active, string headerHash)
    {
        var icons = active
            .Where(c => c.Kind == "Icon")
            .OrderBy(c => c.IconKey ?? c.ComponentId, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file is generated by the icon catalog generator.");
        sb.AppendLine("// Do not edit manually.");
        sb.AppendLine($"// manifest-hash: {headerHash}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("namespace MyChart.Plugins;
");
        sb.AppendLine("/// <summary>Auto-generated catalog of icon descriptors.</summary>");
        sb.AppendLine("public static class IconCatalog");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string ManifestHash = \"{headerHash}\";");
        sb.AppendLine();
        sb.AppendLine("    public readonly record struct Entry(string IconKey, string PathData);");
        sb.AppendLine();
        sb.AppendLine("    public static IReadOnlyList<Entry> All { get; } = new Entry[]");
        sb.AppendLine("    {");
        for (int i = 0; i < icons.Count; i++)
        {
            var ic = icons[i];
            var key = ic.IconKey ?? $"Icon.{ic.ComponentId}";
            var path = ic.GeometryPathData ?? "M0 0 L16 16";
            var comma = i < icons.Count - 1 ? "," : "";
            sb.AppendLine($"        new Entry({CsString(key)}, {CsString(path)}){comma}");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString().Replace("\r\n", "\n");
    }

    private static string CsString(string s)
    {
        // verbatim-ish via regular escaping for determinism
        var escaped = s
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t");
        return "\"" + escaped + "\"";
    }
}
