using MyChart.Core.Plugins.Vocabulary;
using MyChart.Generator.Engine.Operations;
using Xunit;

namespace MyChart.Generator.Tests;

/// <summary>PG3.03 VERIFY — scaffold output; DataTool definition passes validator.</summary>
public class ScaffolderTests
{
    [Fact]
    public void DataToolClick_HasManifestDefinitionDocs_AndValidDefinition()
    {
        var files = Scaffolder.Build(new ScaffoldRequest
        {
            Kind = ScaffoldKind.DataToolClick,
            ComponentId = "TrendLine",
            Name = "Trend Line",
            Anchors = 2
        });

        Assert.True(files.ContainsKey("Manifest.json"));
        Assert.True(files.ContainsKey("Definition.json"));
        Assert.True(files.ContainsKey("Documentation.txt"));

        var err = DefinitionValidator.ValidateJson(files["Definition.json"], out var def);
        Assert.Null(err);
        Assert.NotNull(def);
        Assert.Equal(2, def!.Anchors);
        Assert.Equal("Click", def.Workflow);
        Assert.Contains(def.Shapes, s => s["kind"]?.GetValue<string>() == "Line");
    }

    [Fact]
    public void DataToolClickThenText_ValidDefinition_Anchors1()
    {
        var files = Scaffolder.Build(new ScaffoldRequest
        {
            Kind = ScaffoldKind.DataToolClickThenText,
            ComponentId = "TextNote",
            Name = "Text Note"
        });

        var err = DefinitionValidator.ValidateJson(files["Definition.json"], out var def);
        Assert.Null(err);
        Assert.NotNull(def);
        Assert.Equal(1, def!.Anchors);
        Assert.Equal("ClickThenText", def.Workflow);
        Assert.Contains(def.Shapes, s => s["kind"]?.GetValue<string>() == "Text");
    }

    [Fact]
    public void CodeTool_ProducesSources_WithNamespace()
    {
        var files = Scaffolder.Build(new ScaffoldRequest
        {
            Kind = ScaffoldKind.CodeToolClick,
            ComponentId = "MyMeasure",
            Name = "My Measure",
            Anchors = 2
        });

        Assert.True(files.ContainsKey("MyMeasureTool.cs"));
        Assert.True(files.ContainsKey("MyMeasurePainter.cs"));
        Assert.True(files.ContainsKey("MyMeasureHitTester.cs"));
        Assert.True(files.ContainsKey("MyMeasureRegistration.g.cs"));
        Assert.Contains("namespace MyChart.Plugins.Components.MyMeasure", files["MyMeasureTool.cs"]);
        Assert.Contains("ClickToolBase", files["MyMeasureTool.cs"]);
        Assert.Contains("<auto-generated>", files["MyMeasureRegistration.g.cs"]);
    }

    [Fact]
    public void IconVector_HasGeometry()
    {
        var files = Scaffolder.Build(new ScaffoldRequest
        {
            Kind = ScaffoldKind.IconVector,
            ComponentId = "IconTrendLine",
            Name = "Trend Line Icon",
            IconKey = "Icon.TrendLine"
        });

        Assert.True(files.ContainsKey("Manifest.json"));
        Assert.True(files.ContainsKey("Geometry.txt"));
        Assert.Contains("M2 2", files["Geometry.txt"]);
    }

    [Fact]
    public void Scaffold_IsDeterministic()
    {
        var req = new ScaffoldRequest
        {
            Kind = ScaffoldKind.DataToolClick,
            ComponentId = "TrendLine",
            Name = "Trend Line",
            Anchors = 2
        };
        var a = Scaffolder.Build(req);
        var b = Scaffolder.Build(req);
        Assert.Equal(a.Keys.OrderBy(k => k), b.Keys.OrderBy(k => k));
        foreach (var key in a.Keys)
            Assert.Equal(a[key], b[key]);
    }
}
