// <auto-generated>
// This file is generated by the icon catalog generator.
// Do not edit manually.
// </auto-generated>

namespace MyChart.Plugins;

/// <summary>Auto-generated catalog of icon descriptors.</summary>
public static class IconCatalog
{
    // Populated by generator when icons are added
}
