// <auto-generated>
// This file is generated by the component catalog generator.
// Do not edit manually.
// </auto-generated>

namespace MyChart.Plugins;

/// <summary>Auto-generated catalog of first-party plugin components.</summary>
public static class PluginCatalog
{
    // Populated by generator when components are added (PG later nodes)
}
