// <auto-generated>
// This file is generated by the component catalog generator.
// Do not edit manually.
// </auto-generated>

namespace MyChart.Plugins;

/// <summary>Auto-generated catalog of first-party components (T4.09).</summary>
public static class PluginCatalog
{
    public static readonly string[] DataToolIds =
    {
        "TrendLine", "Rectangle", "Arrow", "Text", "Fibonacci", "Measure"
    };

    public static readonly string[] IconIds =
    {
        "IconCursor", "IconCrosshair", "IconTrendLine", "IconRectangle",
        "IconArrow", "IconText", "IconFibonacci", "IconMeasure",
        "IconSymbol", "IconTimeframe", "IconChartType", "IconIndicators",
        "IconTemplates", "IconLayout", "IconSettings", "IconColor",
        "IconWidth", "IconOpacity", "IconStyle", "IconTemplate",
        "IconLock", "IconClone", "IconDelete"
    };
}
